services:
  - type: web
    name: impulsionar-talentos-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGIN
        value: https://seu-frontend.onrender.com
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true 