services:
  - type: web
    name: impulsionar-talentos-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
                        - key: DATABASE_URL
                    value: postgresql://postgres.eyyaxdotkcwzogtksnol:c2y4cbH0oFgYZkzJ@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        value: impulsionar160716!
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGIN
        value: https://pdi-pathway-builder.vercel.app
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true 