-- =========================================
-- TABELA: checkin_acao
-- =========================================
-- Registra automaticamente ações relacionadas a check-ins com scores baixos (<=3)

create table public.checkin_acao (
  id bigint generated by default as identity primary key,
  id_checkin bigint not null,
  id_user bigint not null,

  tipo_acao text not null,
  -- exemplos:
  -- 'alerta_gestor'
  -- 'chat_agente_ia'
  -- 'encaminhamento_profissional'
  -- 'nenhuma'

  prioridade text not null default 'normal',
  -- 'normal' | 'urgente'

  id_gestor bigint null,
  id_profissional bigint null,

  status text not null default 'pendente',
  -- 'pendente' | 'em_andamento' | 'concluida' | 'cancelada'

  observacoes text null,

  created_at timestamp with time zone not null default now(),
  resolved_at timestamp with time zone null,

  constraint fk_checkin
    foreign key (id_checkin)
    references checkin_emocional (id)
    on delete cascade,
    
  constraint fk_user
    foreign key (id_user)
    references usuarios (id)
    on delete cascade,
    
  constraint fk_gestor
    foreign key (id_gestor)
    references usuarios (id)
    on delete set null,
    
  constraint fk_profissional
    foreign key (id_profissional)
    references profissionais_saude_mental (id)
    on delete set null,
    
  constraint check_tipo_acao
    check (tipo_acao in ('alerta_gestor', 'chat_agente_ia', 'encaminhamento_profissional', 'nenhuma')),
    
  constraint check_prioridade
    check (prioridade in ('normal', 'urgente')),
    
  constraint check_status
    check (status in ('pendente', 'em_andamento', 'concluida', 'cancelada'))
);

create index idx_checkin_acao_id_user on public.checkin_acao(id_user);
create index idx_checkin_acao_id_checkin on public.checkin_acao(id_checkin);
create index idx_checkin_acao_tipo_acao on public.checkin_acao(tipo_acao);
create index idx_checkin_acao_status on public.checkin_acao(status);
create index idx_checkin_acao_created_at on public.checkin_acao(created_at);

-- =========================================
-- TABELA: profissionais_saude_mental
-- =========================================
-- Cadastro de profissionais de saúde mental disponíveis para encaminhamento

create table public.profissionais_saude_mental (
  id bigint generated by default as identity primary key,

  nome text not null,
  tipo_profissional text not null,
  -- 'psicologo' | 'psiquiatra' | 'terapeuta'

  crp_ou_registro text not null unique,
  especialidades text null,

  telefone text null,
  email text null,
  foto_url text null,

  atende_online boolean not null default true,
  atende_presencial boolean not null default false,
  cidade text null,
  estado text null,

  valor_sessao numeric(10,2) null,

  ativo boolean not null default true,

  created_at timestamp with time zone not null default now(),
  
  constraint check_tipo_profissional
    check (tipo_profissional in ('psicologo', 'psiquiatra', 'terapeuta')),
    
  constraint check_estado
    check (estado is null or length(estado) = 2)
);

create index idx_profissional_tipo on public.profissionais_saude_mental(tipo_profissional);
create index idx_profissional_ativo on public.profissionais_saude_mental(ativo);
create index idx_profissional_cidade on public.profissionais_saude_mental(cidade);
create index idx_profissional_estado on public.profissionais_saude_mental(estado);
create index idx_profissional_atende_online on public.profissionais_saude_mental(atende_online);
create index idx_profissional_atende_presencial on public.profissionais_saude_mental(atende_presencial);

-- =========================================
-- ALTERAÇÃO: checkin_emocional
-- =========================================
-- Adicionar coluna gerou_acao se não existir

alter table public.checkin_emocional 
add column if not exists gerou_acao boolean not null default false;

create index if not exists idx_checkin_emocional_gerou_acao on public.checkin_emocional(gerou_acao);
